### ISSUE TITLE
[疑问] 怎么知道对应字母的？

### ISSUE THREAD

**Issue by emako** [SpeedyOrc-C/Genshin-Glyphs#1]
![image](https://user-images.githubusercontent.com/24737061/159099760-a71f81c3-2bbe-4d9d-9def-de0bdf77f866.png)
长得像平假名又不是假名的字符，怎么知道对应字母的？

**Comment by SpeedyOrc-C** [comment]
是通过游戏内的文本推断出来的。如果感兴趣的话，可以去这两个视频看看：
- [稻妻文初步破解](https://www.bilibili.com/video/BV1HV411p7gD)
- [稻妻文进阶翻译](https://www.bilibili.com/video/BV1i44y1v7r7)

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/159142709-9daa004e-36f3-4a7d-a6b0-8e287f3a0568.png)
おもろい！

**Comment by emako** [comment]
发现大佬还有几个字母没做完

**Comment by SpeedyOrc-C** [comment]
不是已经在 README 里面说了还没做完吗？😂

**Comment by emako** [comment]
> 不是已经在 README 里面说了还没做完吗？😂

大佬加油，等大佬做好，我打算移植到SG插件里玩稻妻文
