### ISSUE TITLE
在新活动的牌子上找到了稻妻字母 Q

### ISSUE THREAD

**Issue by MXYLR** [SpeedyOrc-C/Genshin-Glyphs#5]
![稻妻q](https://user-images.githubusercontent.com/37480216/162172586-7f1ea667-ad57-4b3f-9e6f-98bf23705b5e.png)

**Comment by SpeedyOrc-C** [comment]
好，我把它加上去。但这个好像有点麻烦，字形似乎很瘦。

**Comment by SpeedyOrc-C** [comment]
其实这个 Q 和通用字母的 Q 很像。
